image: "gitpod/workspace-full"

tasks:
  - before: "cp .env.example .env"
    init: "npm clean-install"
    command: "npm run dev"

ports:
  - port: 3000
    onOpen: "open-preview"

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: true
