services:
  theoludwig:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: 'theoludwig'
    restart: 'unless-stopped'
    build:
      context: './'
    network_mode: 'host'
    environment:
      PORT: ${PORT-3000}
    env_file: '.env'
