services:
  theoludwig:
    container_name: "theoludwig"
    image: "theoludwig"
    restart: "unless-stopped"
    build:
      context: "./"
      dockerfile: "./apps/website/Dockerfile"
      args:
        VERSION: ${VERSION-0.0.0-develop}
    ports:
      - "${WEBSITE_PORT-3000}:${WEBSITE_PORT-3000}"
    environment:
      PORT: ${WEBSITE_PORT-3000}
    env_file: "./apps/website/.env"
