services:
  divlo.fr:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: 'divlo.fr'
    build:
      context: './'
    ports:
      - '${PORT-3000}:${PORT-3000}'
    environment:
      PORT: ${PORT-3000}
    env_file: './.env'
