packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalogMode: "strict"

catalog:
  # Turborepo
  "turbo": "2.6.3"

  # TypeScript
  "typescript": "5.9.3"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/node": "24.10.3"

  # Utils
  "mime": "4.1.0"

  # React.js/Next.js
  "next": &next "16.0.10"
  "next-intl": "4.6.0"
  "next-themes": "0.4.6"
  "react": "19.2.3"
  "react-dom": "19.2.3"
  "@types/react": "19.2.7"
  "@types/react-dom": "19.2.3"
  "react-icons": "5.5.0"

  # Blog
  "@giscus/react": "3.1.0"
  "gray-matter": "4.0.3"
  "katex": "0.16.27"
  "next-mdx-remote": "5.0.0"
  "@mdx-js/mdx": "3.1.1"
  "rehype-katex": "7.0.1"
  "rehype-raw": "7.0.0"
  "rehype-slug": "6.0.0"
  "remark-gfm": "4.0.1"
  "remark-math": "6.0.0"
  "shiki": "1.24.0"
  "@shikijs/rehype": "1.24.0"

  # Markdown Lint
  "markdownlint-cli2": "0.20.0"
  "markdownlint": "0.40.0"
  "markdownlint-rule-relative-links": "4.2.0"

  # ESLint
  "globals": "16.5.0"
  "typescript-eslint": "8.49.0"
  "eslint": "9.39.1"
  "eslint-config-conventions": "21.1.1"
  "eslint-plugin-promise": "7.2.1"
  "eslint-plugin-unicorn": "62.0.0"
  "eslint-plugin-import-x": "4.16.1"
  "@next/eslint-plugin-next": *next
  "eslint-plugin-react": "7.37.5"
  "eslint-plugin-react-hooks": "7.0.1"

  # Prettier
  "prettier": "3.7.4"
  "prettier-plugin-tailwindcss": "0.7.2"
  "editorconfig-checker": "6.1.1"

  # Storybook
  "storybook": &storybook "10.1.8"
  "@storybook/addon-docs": *storybook
  "@storybook/addon-a11y": *storybook
  "@storybook/nextjs": *storybook
  "@storybook/addon-themes": *storybook
  "@storybook/test-runner": "0.24.2"
  "@chromatic-com/storybook": "4.1.3"
  "chromatic": "13.3.4"

  # Testing
  "playwright": &playwright "1.57.0"
  "@playwright/test": *playwright
  "start-server-and-test": "2.1.3"

  # CSS
  "postcss": "8.5.6"
  "@tailwindcss/postcss": "4.1.18"
  "@tailwindcss/typography": "0.5.19"
  "tailwindcss": "4.1.18"
  "tailwind-merge": "3.4.0"
  "clsx": "2.1.1"
  "cva": "1.0.0-beta.4"
  "@fontsource/montserrat": "5.2.8"

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "core-js-pure"
  - "esbuild"
  - "sharp"
  - "unrs-resolver"
  - "@parcel/watcher"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
