packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalog:
  # Turborepo
  "turbo": "2.5.3"

  # Utils
  "mime": "4.0.7"

  # React.js/Next.js
  "next": &next "15.3.2"
  "next-intl": "4.1.0"
  "next-themes": "0.4.6"
  "react": "19.1.0"
  "react-dom": "19.1.0"
  "react-icons": "5.5.0"
  "@types/react": "19.1.3"
  "@types/react-dom": "19.1.3"

  # Blog
  "@giscus/react": "3.1.0"
  "gray-matter": "4.0.3"
  "katex": "0.16.22"
  "next-mdx-remote": "5.0.0"
  "@mdx-js/mdx": "3.1.0"
  "rehype-katex": "7.0.1"
  "rehype-raw": "7.0.0"
  "rehype-slug": "6.0.0"
  "remark-gfm": "4.0.1"
  "remark-math": "6.0.0"
  "shiki": "1.24.0"
  "@shikijs/rehype": "1.24.0"

  # Markdown Lint
  "markdownlint-cli2": "0.18.0"
  "markdownlint": "0.38.0"
  "markdownlint-rule-relative-links": "4.1.0"

  # TypeScript
  "typescript": "5.8.3"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/node": "22.15.17"

  # ESLint
  "globals": "16.1.0"
  "typescript-eslint": "8.32.0"
  "@eslint/eslintrc": "3.3.1"
  "eslint": "9.26.0"
  "eslint-config-conventions": "19.2.0"
  "eslint-plugin-promise": "7.2.1"
  "eslint-plugin-unicorn": "59.0.1"
  "eslint-config-next": *next
  "eslint-plugin-import-x": "4.11.1"

  # Prettier
  "prettier": "3.5.3"
  "prettier-plugin-tailwindcss": "0.6.11"
  "editorconfig-checker": "6.0.1"

  # Storybook
  "storybook": &storybook "8.6.12"
  "@storybook/addon-essentials": *storybook
  "@storybook/addon-storysource": *storybook
  "@storybook/addon-a11y": *storybook
  "@storybook/addon-interactions": *storybook
  "@storybook/blocks": *storybook
  "@storybook/nextjs": *storybook
  "@storybook/react": *storybook
  "@storybook/test": *storybook
  "@storybook/addon-themes": *storybook
  "@storybook/test-runner": "0.22.0"
  "@chromatic-com/storybook": "3.2.6"
  "chromatic": "11.28.2"
  "storybook-dark-mode": "4.0.2"

  # Testing
  "playwright": &playwright "1.52.0"
  "@playwright/test": *playwright
  "axe-playwright": "2.1.0"
  "start-server-and-test": "2.0.11"

  # CSS
  "postcss": "8.5.3"
  "@tailwindcss/postcss": "4.1.6"
  "@tailwindcss/typography": "0.5.16"
  "tailwindcss": "4.1.6"
  "tailwind-merge": "3.2.0"
  "clsx": "2.1.1"
  "cva": "1.0.0-beta.3"
  "@fontsource/montserrat": "5.2.5"

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "core-js-pure"
  - "esbuild"
  - "sharp"
  - "unrs-resolver"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
