packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalogMode: "strict"

catalog:
  # Turborepo
  "turbo": "2.8.9"

  # TypeScript/Linting
  "typescript": "5.9.3"
  "@types/node": "25.2.3"
  "@total-typescript/ts-reset": "0.6.1"
  "oxlint": "1.47.0"
  "oxlint-tsgolint": "0.12.2"
  "oxfmt": "0.32.0"
  "eslint-config-conventions": "21.2.0"
  "editorconfig-checker": "6.1.1"

  # Utils
  "mime": "4.1.0"

  # React.js/Next.js
  "next": "16.1.6"
  "next-intl": "4.8.3"
  "next-themes": "0.4.6"
  "react": "19.2.4"
  "react-dom": "19.2.4"
  "@types/react": "19.2.14"
  "@types/react-dom": "19.2.3"
  "react-icons": "5.5.0"

  # Blog
  "@giscus/react": "3.1.0"
  "gray-matter": "4.0.3"
  "katex": "0.16.28"
  "next-mdx-remote": "5.0.0"
  "@mdx-js/mdx": "3.1.1"
  "rehype-katex": "7.0.1"
  "rehype-raw": "7.0.0"
  "rehype-slug": "6.0.0"
  "remark-gfm": "4.0.1"
  "remark-math": "6.0.0"
  "shiki": "1.24.0"
  "@shikijs/rehype": "1.24.0"

  # Markdown Lint
  "markdownlint-cli2": "0.21.0"
  "markdownlint": "0.40.0"
  "markdownlint-rule-relative-links": "5.0.1"

  # Storybook
  "storybook": &storybook "10.2.8"
  "@storybook/addon-docs": *storybook
  "@storybook/addon-a11y": *storybook
  "@storybook/nextjs": *storybook
  "@storybook/addon-themes": *storybook
  "@storybook/test-runner": "0.24.2"
  "@chromatic-com/storybook": "5.0.1"
  "chromatic": "15.1.0"

  # Testing
  "playwright": &playwright "1.58.2"
  "@playwright/test": *playwright
  "start-server-and-test": "2.1.3"

  # CSS
  "postcss": "8.5.6"
  "@tailwindcss/postcss": "4.1.18"
  "@tailwindcss/typography": "0.5.19"
  "tailwindcss": "4.1.18"
  "tailwind-merge": "3.4.1"
  "clsx": "2.1.1"
  "@fontsource/montserrat": "5.2.8"

allowBuilds:
  "@swc/core": true
  "@parcel/watcher": true
  "sharp": true
  "unrs-resolver": true
  "core-js-pure": true
  "esbuild": true
