packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Turborepo and Releases
  "turbo": "2.3.3"
  "@saithodev/semantic-release-backmerge": "4.0.1"
  "@semantic-release/exec": "6.0.3"
  "@semantic-release/git": "10.0.1"
  "semantic-release": "23.1.1"
  "replace-in-files-cli": "3.0.0"

  # Utils
  "deepmerge": "4.3.1"

  # React.js/Next.js
  "next": "15.0.4"
  "next-intl": "3.26.0"
  "next-themes": "0.4.4"
  "react": "19.0.0"
  "react-dom": "19.0.0"
  "react-icons": "5.4.0"
  "@types/react": "19.0.0"
  "@types/react-dom": "19.0.0"

  # Blog
  "@giscus/react": "3.0.0"
  "gray-matter": "4.0.3"
  "katex": "0.16.11"
  "next-mdx-remote": "5.0.0"
  "@mdx-js/mdx": "3.1.0"
  "rehype-katex": "7.0.1"
  "rehype-raw": "7.0.0"
  "rehype-slug": "6.0.0"
  "remark-gfm": "4.0.0"
  "remark-math": "6.0.0"
  "shiki": "1.24.0"
  "@shikijs/rehype": "1.24.0"

  # Markdown Lint
  "markdownlint-cli2": "0.15.0"
  "markdownlint": "0.36.1"
  "markdownlint-rule-relative-links": "3.0.0"

  # TypeScript
  "typescript": "5.7.2"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/node": "22.10.1"

  # ESLint
  "globals": "15.13.0"
  "typescript-eslint": "8.17.0"
  "@eslint/eslintrc": "3.2.0"
  "eslint": "9.16.0"
  "eslint-config-conventions": "17.0.1"
  "eslint-plugin-promise": "7.2.1"
  "eslint-plugin-unicorn": "56.0.1"
  "eslint-config-next": "15.0.4"
  "eslint-plugin-storybook": "0.11.1"
  "eslint-plugin-tailwindcss": "3.17.5"
  "eslint-plugin-import-x": "4.5.0"

  # Prettier
  "prettier": "3.4.2"
  "prettier-plugin-tailwindcss": "0.6.9"
  "editorconfig-checker": "6.0.0"

  # Storybook
  "@chromatic-com/storybook": "3.2.2"
  "@storybook/addon-a11y": "8.4.7"
  "@storybook/addon-essentials": "8.4.7"
  "@storybook/addon-interactions": "8.4.7"
  "@storybook/addon-storysource": "8.4.7"
  "@storybook/addon-themes": "8.4.7"
  "@storybook/blocks": "8.4.7"
  "@storybook/nextjs": "8.4.7"
  "@storybook/react": "8.4.7"
  "@storybook/test": "8.4.7"
  "@storybook/test-runner": "0.20.1"
  "chromatic": "11.20.0"
  "http-server": "14.1.1"
  "storybook": "8.4.7"
  "storybook-dark-mode": "4.0.2"

  # Testing
  "playwright": "1.49.0"
  "@playwright/test": "1.49.0"
  "axe-playwright": "2.0.3"
  "start-server-and-test": "2.0.8"
  "@vitest/browser": "2.1.8"
  "@vitest/coverage-v8": "2.1.8"
  "@vitest/ui": "2.1.8"
  "vitest": "2.1.8"
  "@testing-library/react": "16.1.0"

  # CSS
  "postcss": "8.4.49"
  "tailwindcss": "3.4.16"
  "@tailwindcss/typography": "0.5.15"
  "tailwind-merge": "2.5.5"
  "clsx": "2.1.1"
  "cva": "1.0.0-beta.2"
  "@fontsource/montserrat": "5.1.0"
