packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalogMode: "strict"

catalog:
  # Turborepo
  "turbo": "2.9.9"

  # TypeScript/Linting
  "typescript": "6.0.3"
  "@types/node": "25.6.0"
  "@total-typescript/ts-reset": "0.6.1"
  "oxlint": "1.63.0"
  "oxlint-tsgolint": "0.22.1"
  "oxfmt": "0.48.0"
  "eslint-config-conventions": "21.4.0"
  "editorconfig-checker": "6.1.1"

  # Utils
  "mime": "4.1.0"

  # React.js/Next.js
  "next": "16.2.4"
  "next-intl": "4.11.0"
  "next-themes": "0.4.6"
  "react": "19.2.5"
  "react-dom": "19.2.5"
  "@types/react": "19.2.14"
  "@types/react-dom": "19.2.3"
  "react-icons": "5.6.0"

  # Blog
  "@giscus/react": "3.1.0"
  "gray-matter": "4.0.3"
  "katex": "0.16.45"
  "next-mdx-remote": "5.0.0"
  "@mdx-js/mdx": "3.1.1"
  "rehype-katex": "7.0.1"
  "rehype-raw": "7.0.0"
  "rehype-slug": "6.0.0"
  "remark-gfm": "4.0.1"
  "remark-math": "6.0.0"
  "shiki": "1.24.0"
  "@shikijs/rehype": "1.24.0"

  # Markdown Lint
  "markdownlint-cli2": "0.22.1"
  "markdownlint": "0.40.0"
  "markdownlint-rule-relative-links": "5.1.0"

  # Storybook
  "storybook": &storybook "10.3.6"
  "@storybook/addon-docs": *storybook
  "@storybook/addon-a11y": *storybook
  "@storybook/nextjs": *storybook
  "@storybook/addon-themes": *storybook
  "@storybook/test-runner": "0.24.3"
  "@chromatic-com/storybook": "5.1.2"
  "chromatic": "16.8.0"

  # Testing
  "playwright": &playwright "1.59.1"
  "@playwright/test": *playwright
  "start-server-and-test": "3.0.2"

  # CSS
  "postcss": "8.5.14"
  "tailwindcss": &tailwindcss "4.2.4"
  "@tailwindcss/postcss": *tailwindcss
  "@tailwindcss/typography": "0.5.19"
  "tailwind-merge": "3.5.0"
  "clsx": "2.1.1"
  "@fontsource/montserrat": "5.2.8"

allowBuilds:
  "@swc/core": true
  "@parcel/watcher": true
  "sharp": true
  "unrs-resolver": true
  "core-js-pure": true
  "esbuild": true
