packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Turborepo and Releases
  "turbo": "2.2.3"
  "@saithodev/semantic-release-backmerge": "4.0.1"
  "@semantic-release/exec": "6.0.3"
  "@semantic-release/git": "10.0.1"
  "semantic-release": "23.1.1"
  "replace-in-files-cli": "3.0.0"

  # Utils
  "deepmerge": "4.3.1"

  # React.js/Next.js
  "next": "15.0.3"
  "next-intl": "3.25.0"
  "next-themes": "0.4.3"
  "react": "18.3.1"
  "react-dom": "18.3.1"
  "react-icons": "5.3.0"
  "@types/react": "18.3.12"
  "@types/react-dom": "18.3.1"

  # Blog
  "@giscus/react": "3.0.0"
  "gray-matter": "4.0.3"
  "katex": "0.16.11"
  "next-mdx-remote": "5.0.0"
  "@mdx-js/mdx": "3.0.1"
  "rehype-katex": "7.0.1"
  "rehype-raw": "7.0.0"
  "rehype-slug": "6.0.0"
  "remark-gfm": "4.0.0"
  "remark-math": "6.0.0"
  "shiki": "1.12.0"
  "@shikijs/rehype": "1.12.0"

  # Markdown Lint
  "markdownlint-cli2": "0.14.0"
  "markdownlint": "0.35.0"
  "markdownlint-rule-relative-links": "3.0.0"

  # TypeScript
  "typescript": "5.6.3"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/node": "22.9.0"

  # ESLint
  "globals": "15.12.0"
  "typescript-eslint": "8.13.0"
  "@eslint/eslintrc": "3.1.0"
  "eslint": "9.14.0"
  "eslint-config-conventions": "17.0.0"
  "eslint-plugin-promise": "7.1.0"
  "eslint-plugin-unicorn": "56.0.0"
  "eslint-config-next": "15.0.3"
  "eslint-plugin-storybook": "0.11.0"
  "eslint-plugin-tailwindcss": "3.17.5"
  "eslint-plugin-import-x": "4.4.0"

  # Prettier
  "prettier": "3.3.3"
  "prettier-plugin-tailwindcss": "0.6.8"
  "editorconfig-checker": "6.0.0"

  # Storybook
  "@chromatic-com/storybook": "3.2.2"
  "@storybook/addon-a11y": "8.4.2"
  "@storybook/addon-essentials": "8.4.2"
  "@storybook/addon-interactions": "8.4.2"
  "@storybook/addon-storysource": "8.4.2"
  "@storybook/addon-themes": "8.4.2"
  "@storybook/blocks": "8.4.2"
  "@storybook/nextjs": "8.4.2"
  "@storybook/react": "8.4.2"
  "@storybook/test": "8.4.2"
  "@storybook/test-runner": "0.19.1"
  "chromatic": "11.18.0"
  "http-server": "14.1.1"
  "storybook": "8.4.2"
  "storybook-dark-mode": "4.0.2"

  # Testing
  "playwright": "1.48.2"
  "@playwright/test": "1.48.2"
  "axe-playwright": "2.0.3"
  "start-server-and-test": "2.0.8"
  "@vitest/browser": "2.1.4"
  "@vitest/coverage-v8": "2.1.4"
  "@vitest/ui": "2.1.4"
  "vitest": "2.1.4"
  "@testing-library/react": "16.0.1"

  # CSS
  "postcss": "8.4.47"
  "tailwindcss": "3.4.14"
  "@tailwindcss/typography": "0.5.15"
  "tailwind-merge": "2.5.4"
  "clsx": "2.0.0"
  "cva": "1.0.0-beta.1"
  "@fontsource/montserrat": "5.1.0"
