packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalog:
  # Turborepo
  "turbo": "2.4.0"

  # Utils
  "mime": "4.0.6"

  # React.js/Next.js
  "next": &next "15.1.6"
  "next-intl": "3.26.3"
  "next-themes": "0.4.4"
  "nuqs": "2.3.2"
  "react": "19.0.0"
  "react-dom": "19.0.0"
  "react-icons": "5.4.0"
  "@types/react": "19.0.8"
  "@types/react-dom": "19.0.3"

  # Blog
  "@giscus/react": "3.1.0"
  "gray-matter": "4.0.3"
  "katex": "0.16.21"
  "next-mdx-remote": "5.0.0"
  "@mdx-js/mdx": "3.1.0"
  "rehype-katex": "7.0.1"
  "rehype-raw": "7.0.0"
  "rehype-slug": "6.0.0"
  "remark-gfm": "4.0.0"
  "remark-math": "6.0.0"
  "shiki": "1.24.0"
  "@shikijs/rehype": "1.24.0"

  # Markdown Lint
  "markdownlint-cli2": "0.17.2"
  "markdownlint": "0.37.4"
  "markdownlint-rule-relative-links": "4.0.1"

  # TypeScript
  "typescript": "5.7.3"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/node": "22.13.1"

  # ESLint
  "globals": "15.14.0"
  "typescript-eslint": "8.23.0"
  "@eslint/eslintrc": "3.2.0"
  "eslint": "9.20.0"
  "eslint-config-conventions": "18.0.2"
  "eslint-plugin-promise": "7.2.1"
  "eslint-plugin-unicorn": "56.0.1"
  "eslint-config-next": *next
  "eslint-plugin-storybook": "0.11.2"
  "eslint-plugin-tailwindcss": "3.18.0"
  "eslint-plugin-import-x": "4.6.1"

  # Prettier
  "prettier": "3.4.2"
  "prettier-plugin-tailwindcss": "0.6.11"
  "editorconfig-checker": "6.0.1"

  # Storybook
  "storybook": &storybook "8.5.3"
  "@storybook/addon-essentials": *storybook
  "@storybook/addon-storysource": *storybook
  "@storybook/addon-a11y": *storybook
  "@storybook/addon-interactions": *storybook
  "@storybook/blocks": *storybook
  "@storybook/nextjs": *storybook
  "@storybook/react": *storybook
  "@storybook/test": *storybook
  "@storybook/addon-themes": *storybook
  "@storybook/test-runner": "0.21.0"
  "@chromatic-com/storybook": "3.2.4"
  "chromatic": "11.25.2"
  "storybook-dark-mode": "4.0.2"

  # Testing
  "playwright": &playwright "1.50.1"
  "@playwright/test": *playwright
  "axe-playwright": "2.1.0"
  "start-server-and-test": "2.0.10"

  # CSS
  "postcss": "8.5.1"
  "tailwindcss": "3.4.17"
  "@tailwindcss/typography": "0.5.15"
  "tailwind-merge": "2.6.0"
  "clsx": "2.1.1"
  "cva": "1.0.0-beta.3"
  "@fontsource/montserrat": "5.1.1"
