name: "Build"

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.1.6"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v4.0.2"
        with:
          node-version: "20.x"
          cache: "npm"

      - name: "Install dependencies"
        run: "npm clean-install"

      - name: "Build"
        run: "npm run build"
