name: "Release"

on:
  push:
    branches: [main, staging]

jobs:
  release:
    timeout-minutes: 30
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      issues: "write"
      pull-requests: "write"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v4.2.2"
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Import GPG key"
        uses: "crazy-max/ghaction-import-gpg@v6.1.0"
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - uses: "pnpm/action-setup@v4.0.0"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v4.1.0"
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: "Install dependencies"
        run: "pnpm install --frozen-lockfile"

      - name: "Release"
        run: "node --run release"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_EMAIL }}
