name: 'Release'

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3.3.0'
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 'Import GPG key'
        uses: 'crazy-max/ghaction-import-gpg@v4'
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v3.6.0'
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: 'Install'
        run: 'npm install'

      - name: 'Release'
        run: 'npm run release'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_EMAIL }}

      - name: 'Deploy to Vercel'
        run: 'npm run deploy -- --token="${VERCEL_TOKEN}" --prod'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
