name: "Release"

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.0.0"
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Import GPG key"
        uses: "crazy-max/ghaction-import-gpg@v6.0.0"
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: "Setup Node.js"
        uses: "actions/setup-node@v3.8.1"
        with:
          node-version: "20.x"
          cache: "npm"

      - name: "Install dependencies"
        run: "npm clean-install"

      - name: "Release"
        run: "npm run release"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_EMAIL }}
