name: 'Test'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  test-unit:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3.5.3'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3.6.0'
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: 'Install dependencies'
        run: 'npm clean-install'

      - name: 'Unit Test'
        run: 'npm run test:unit'

  test-e2e:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3.5.3'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3.6.0'
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: 'Install dependencies'
        run: 'npm clean-install'

      - name: 'Build'
        run: 'npm run build'

      - name: 'html-w3c-validator'
        run: 'npm run test:html-w3c-validator'

      - name: 'End To End (e2e) Test'
        run: 'npm run test:e2e'
